Repository junglesub/hgu-oss-miniproject, pull requests merged in 2021-05, with the labels that each got.

#8 포인터 배열로 변경하였습니다.
  record.h
Labels: enhancement

#27 Create, Update 함수 구현
  .gitignore
  record.c
  record.h
Labels: WK10, enhancement

#24 CRUD: Read Data
  .gitignore
  main.c
  record
  record.c
  record.h
Labels: WK10, enhancement

#39 타입을 한글로 알려준다!
  record.c
  record.h
Labels: enhancement

#23 Jungsub/delete entry
  .vscode/settings.json
  main.c
  record.c
  record.h
Labels: WK10, enhancement

#51 Update 기능을 메뉴에 추가했습니다.
  .gitignore
  main.c
  record.c
Labels: WK10, enhancement

#61 출력형태 및 한국어 수정
  record.c
Labels: enhancement

#63 항목별 내용 검색 구현 완료
  main.c
  record.c
  record.h
  records.txt
  tempCodeRunnerFile.c
Labels: WK11, enhancement
